modLoader="javafml"
loaderVersion="[36,)"
license="MIT"

[[mods]]
modId="jperluxomod"
version="${version}"
displayName="JPerluxo Mod"
description='''A simple mod with some new features for "Minecraft: Java Edition" on pc.'''
logoFile="logo.png"
credits="JPerluxo"
authors="JPerluxo"

[[dependencies.jperluxomod]]
  modId="forge"
  mandatory=true
  versionRange="[36,)"
  ordering="NONE"
  side="BOTH"

[[dependencies.jperluxomod]]
  modId="minecraft"
  mandatory=true
  versionRange="[1.16.5,1.17)"
  ordering="NONE"
  side="BOTH"
